### ISSUE TITLE
how to compile this project?

### ISSUE THREAD

**Issue by albertyou2** [stereomatchingkiss/pedestrian_flow_counter_by_opencv#1]
@stereomatchingkiss  hi
is there any makefile for 'make' it?
I am under the Ubuntu 16.04 with gcc/g++ 5.4

**Comment by stereomatchingkiss** [comment]
The makefile of this project is generated by "qmake", you need to install
Qt5 to generate the makefile for you.
I would like to refactor this project a little bit, maybe on this weekend.
Will update the instructions of compilation.

2017-02-03 14:35 GMT+08:00 albertyou2 <notifications@github.com>:

**Comment by albertyou2** [comment]
right,thank you for help!

**Comment by stereomatchingkiss** [comment]
I update the project, if you still got problems, please ask, I am happy to help.
Remember to call "git pull", I make lots of changes(for readability).

**Comment by albertyou2** [comment]
thanks ! it's a very good instructions! 
it is a little difficult for me because i never used QT before,but i will spend time to try it.

I notice that you mentioned that i should install opencv 3.2 on my PC,I wondering if open3.1 could also make it work ? If it could ,i need't reinstall opencv(i install 3.1.0 on my pc).

thank you again!

**Comment by stereomatchingkiss** [comment]
opencv3.1 also work, if you are using windows, you need to change the
"CV_LIB_VER = 320" in cv_dev.pri to
"CV_LIB_VER = 310"

2017-02-04 14:36 GMT+08:00 albertyou2 <notifications@github.com>:

**Comment by albertyou2** [comment]
hi i think i run the project successful,but when i enter the video path and return ,the window closed and nothing happen .

when i click 'run' button ,a shell window shown like this : 
![ba1655d0-0ab3-404c-88bf-2787a870bd87](https://cloud.githubusercontent.com/assets/11494761/22616772/d4c337be-eaee-11e6-9362-d615540a3dcd.png)

Am i missing something?

**Comment by stereomatchingkiss** [comment]
You need to specify the path of the video, as the readme.md
<https://github.com/stereomatchingkiss/pedestrian_flow_counter_by_opencv>
mentioned(step 12).
Or you could open the app from command line, second parameter indicate the
path of video as following

"people_counter /home/ramsus/video/peopleCounter.avi"

You can download peopleCounter.avi from here
<https://mega.nz/#!w59VUCjI!qM5xMwFYK5_ZDYpM6YVlRGqG_Mrs9B9W6P3x2xmuYjk>.

ps : Remember to call git pull, fixed a bug.



2017-02-04 15:30 GMT+08:00 albertyou2 <notifications@github.com>:

**Comment by albertyou2** [comment]
hi , I run this project successful! 
Thank you for your great work and help!
now close this issue!
